# Configuración del dataset para útiles escolares
# Universidad Politécnica de Chiapas
# Proyecto: Detector de Útiles Escolares con YOLO

# Rutas del dataset
path: ./dataset  # Ruta base del dataset
train: images/train  # Carpeta de imágenes de entrenamiento
val: images/val      # Carpeta de imágenes de validación

# Número de clases
nc: 3

# Nombres de las clases (en orden de índice)
names:
  0: lapiz           # Clase 0: Lápices individuales
  1: cuaderno        # Clase 1: Cuadernos individuales  
  2: kit_escritura   # Clase 2: Lápiz y cuaderno juntos

# Metadatos del proyecto
project_info:
  name: "Detector de Útiles Escolares"
  university: "Universidad Politécnica de Chiapas"
  course: "Multimedia y Diseño Digital"
  authors: ["Estudiante 1", "Estudiante 2"]
  description: "Sistema de detección de lápices, cuadernos y kits de escritura usando YOLO personalizado"

# Configuración de entrenamiento recomendada
training_config:
  epochs: 150           # Número de epochs (aumentado para mejor aprendizaje)
  batch_size: 16        # Tamaño del batch (ajustar según GPU)
  img_size: 640         # Tamaño de imagen
  learning_rate: 0.01   # Tasa de aprendizaje
  patience: 30          # Paciencia para early stopping
  
# Objetivos de métricas
target_metrics:
  map50: 0.75          # mAP a IoU=0.5
  precision: 0.80      # Precisión objetivo
  recall: 0.75         # Recall objetivo

# Información específica de cada clase
class_details:
  lapiz:
    description: "Instrumentos de escritura individuales (lápices de grafito, mecánicos, de colores)"
    target_images: 60
    difficulty: "Media"
    tips: "Capturar diferentes ángulos, colores y estados (nuevo/usado)"
    
  cuaderno:
    description: "Libretas y cuadernos para escribir o dibujar (cerrados y abiertos)"
    target_images: 60
    difficulty: "Baja"
    tips: "Incluir diferentes tamaños, tipos (espiral, cosido) y estados"
    
  kit_escritura:
    description: "Lápiz y cuaderno juntos en el mismo contexto de uso"
    target_images: 80
    difficulty: "Alta"
    tips: "CLASE CLAVE - Múltiples configuraciones de lápiz+cuaderno juntos"

# Distribución del dataset
dataset_split:
  train_percentage: 80
  val_percentage: 20
  minimum_images_per_class: 50
  recommended_images_per_class: 75

# Configuración de anotación
annotation_guidelines:
  format: "YOLO"
  tool_recommended: "LabelImg"
  alternative_tool: "Roboflow"
  bbox_guidelines:
    - "Ajustar cajas lo más cerca posible al objeto"
    - "Para kit_escritura: una sola caja incluyendo ambos objetos"
    - "Evitar objetos parcialmente ocultos"
    - "Mantener consistencia en la anotación"

# Contexto del modelo preentrenado
pretrained_context:
  model: "YOLOv8"
  relevant_classes: ["book", "person", "chair", "dining table", "laptop", "cell phone"]
  purpose: "Detectar contexto escolar y educativo donde aparecen los útiles"